plugins {
    id 'com.android.library'
}

android {
    namespace 'com.startapp.mediation.admob'

    compileSdk 36

    defaultConfig {
        minSdk 23
        targetSdk 36

        buildConfigField 'String', 'VERSION_NAME', "\"$versionName\""
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    api 'com.google.android.gms:play-services-ads:[24,25)'
    api 'com.startapp:inapp-sdk:[5.2.2,6)'
}

apply from: 'https://raw.githubusercontent.com/StartApp-SDK/sonatype-central-publish/refs/heads/main/sonatype-central-publish.gradle'
